#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Droid.Resource", IsApplication=true)]

namespace App1.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030002
			public const int accent = 2130903042;
			
			// aapt resource value: 0x7f030000
			public const int primary = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int primaryDark = 2130903041;
			
			// aapt resource value: 0x7f030004
			public const int splash_background = 2130903044;
			
			// aapt resource value: 0x7f030003
			public const int window_background = 2130903043;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int contact_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int directions_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int help_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int map_icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int menu_icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int RhinoRust = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int RhinoRust_style = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int scavenger_icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int settings_icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int storyline_icon = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int application_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
