//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moma {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppLanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moma.AppLanguageResource", typeof(AppLanguageResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently an active storyline, are you sure you want to start a new one?.
        /// </summary>
        internal static string ActiveQuestion {
            get {
                return ResourceManager.GetString("ActiveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Storyline.
        /// </summary>
        internal static string ActiveStoryline {
            get {
                return ResourceManager.GetString("ActiveStoryline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1001, Lenoir St., local E-206. Montreal,Quebec, H4C 2Z6.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string AddressTitle {
            get {
                return ResourceManager.GetString("AddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➥ Get on Autoroute 40 towards the Autoroute 15
        ///
        ///➥ Take Autoroute 15 S
        ///
        ///➥ Take Autoroute 720 E
        ///
        ///➥ Exit at Rue Saint Antoine O
        ///
        ///➥ Turn Right on Rue Lacasse .
        /// </summary>
        internal static string CarDirections {
            get {
                return ResourceManager.GetString("CarDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Directions via Car.
        /// </summary>
        internal static string CarDirectionsTitle {
            get {
                return ResourceManager.GetString("CarDirectionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default language is English. It may be changed at any time in the settings..
        /// </summary>
        internal static string DefaultLanguage {
            get {
                return ResourceManager.GetString("DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➥ Arrive at 1001 Rue Lenoir on Right.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Museum Directions.
        /// </summary>
        internal static string Directions {
            get {
                return ResourceManager.GetString("Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display and exhibitions language.
        /// </summary>
        internal static string LanguageDef {
            get {
                return ResourceManager.GetString("LanguageDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected language.
        /// </summary>
        internal static string LanguageSelection {
            get {
                return ResourceManager.GetString("LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Tour.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to the internet.
        /// </summary>
        internal static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday 2 p.m. à 5 p.m.
        ///Saturday 2 p.m. à 5 p.m.
        ///Sunday 2 p.m. à 5 p.m.
        ///Wednesday (Appointment only)
        ///Groups by appointment at anytime..
        /// </summary>
        internal static string OpeningHours {
            get {
                return ResourceManager.GetString("OpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Hours.
        /// </summary>
        internal static string OpeningHoursTitle {
            get {
                return ResourceManager.GetString("OpeningHoursTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone : (514) 932-9663.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string PhoneTitle {
            get {
                return ResourceManager.GetString("PhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup.
        /// </summary>
        internal static string Popup {
            get {
                return ResourceManager.GetString("Popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic popups during exhibitions.
        /// </summary>
        internal static string PopupDef {
            get {
                return ResourceManager.GetString("PopupDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult: 5 $
        ///Student: 3 $
        ///Family: 10 $
        ///Groups (5+) : 3 $ each.
        /// </summary>
        internal static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        internal static string PricingTitle {
            get {
                return ResourceManager.GetString("PricingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Application.
        /// </summary>
        internal static string ResetApp {
            get {
                return ResourceManager.GetString("ResetApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application will restart automatically..
        /// </summary>
        internal static string ResetMsg {
            get {
                return ResourceManager.GetString("ResetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Application?.
        /// </summary>
        internal static string ResetTitle {
            get {
                return ResourceManager.GetString("ResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scavenger Hunt.
        /// </summary>
        internal static string Scavenger {
            get {
                return ResourceManager.GetString("Scavenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Url.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url from which all medias are being loaded from.
        /// </summary>
        internal static string ServerDef {
            get {
                return ResourceManager.GetString("ServerDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings were modified. The language will be updated upon the next restart of the application..
        /// </summary>
        internal static string SettingsChanged {
            get {
                return ResourceManager.GetString("SettingsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings modified.
        /// </summary>
        internal static string SettingsChangedTitle {
            get {
                return ResourceManager.GetString("SettingsChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds for notifications.
        /// </summary>
        internal static string SoundDef {
            get {
                return ResourceManager.GetString("SoundDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➥ Exit at Place Saint-Henri metro station
        ///
        ///➥ Turn left onto Rue Saint-Jacques
        ///
        ///➥ Turn Right onto Rue Lenoir.
        /// </summary>
        internal static string STMDirections {
            get {
                return ResourceManager.GetString("STMDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Directions via STM.
        /// </summary>
        internal static string STMDirectionsTitle {
            get {
                return ResourceManager.GetString("STMDirectionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storylines.
        /// </summary>
        internal static string Storyline {
            get {
                return ResourceManager.GetString("Storyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration.
        /// </summary>
        internal static string Vibration {
            get {
                return ResourceManager.GetString("Vibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone vibrations for notifications.
        /// </summary>
        internal static string VibrationDef {
            get {
                return ResourceManager.GetString("VibrationDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://moeb.ca/en.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string WebsiteTitle {
            get {
                return ResourceManager.GetString("WebsiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
